/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gastos;

import Datos.CategoriaXml;
import clases.Categoria;
import clases.Movimientos;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Michele
 */
public class AgregarCategoria extends javax.swing.JFrame {
CategoriaXml datoscat = new CategoriaXml();
ventana1 ventana;
    /**
     * Creates new form AgregarCategoria
     */
    public AgregarCategoria() {
        initComponents();
       this.setLocationRelativeTo(null);
       this.setResizable(false); 
       this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        categoriaTxt = new javax.swing.JTextField();
        agregarboton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre:");

        categoriaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                categoriaTxtKeyPressed(evt);
            }
        });

        agregarboton.setText("Agregar");
        agregarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarbotonActionPerformed(evt);
            }
        });
        agregarboton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agregarbotonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(categoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarboton)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(categoriaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarboton))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarbotonActionPerformed
try{   
     Categoria cat = new Categoria(categoriaTxt.getText());
       datoscat.agregarCategoria(cat);
     
   JOptionPane.showMessageDialog(null, " ha sido agregado con exito!","Agregado", JOptionPane.INFORMATION_MESSAGE);
   this.dispose();
 ventana1.trampa.doClick();
   }
   catch(Exception e){
       JOptionPane.showMessageDialog(null, "Error al Agregar", "Error", JOptionPane.ERROR_MESSAGE);
         
    }
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_agregarbotonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void agregarbotonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agregarbotonKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
       try{   
     Categoria cat = new Categoria(categoriaTxt.getText());
       datoscat.agregarCategoria(cat);
     
   JOptionPane.showMessageDialog(null, " ha sido agregado con exito!","Agregado", JOptionPane.INFORMATION_MESSAGE);
   this.dispose();
 ventana1.trampa.doClick();
   }
   catch(Exception ex){
       JOptionPane.showMessageDialog(null, "Error al Agregar", "Error", JOptionPane.ERROR_MESSAGE);
         
    }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_agregarbotonKeyPressed

    private void categoriaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoriaTxtKeyPressed
 if (evt.getKeyCode()==KeyEvent.VK_ENTER){
       try{   
     Categoria cat = new Categoria(categoriaTxt.getText());
       datoscat.agregarCategoria(cat);
     
   JOptionPane.showMessageDialog(null, " ha sido agregado con exito!","Agregado", JOptionPane.INFORMATION_MESSAGE);
   this.dispose();
 ventana1.trampa.doClick();
   }
   catch(Exception ex){
       JOptionPane.showMessageDialog(null, "Error al Agregar", "Error", JOptionPane.ERROR_MESSAGE);
         
    }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarboton;
    private javax.swing.JTextField categoriaTxt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
